version: '3'
services:
  app:
    container_name: ${TEST_POLYGLOAT_CONTAINER_NAME}
    image: polygloat/polygloat:${TEST_POLYGLOAT_SERVER_VERSION}
    ports:
      - "${TEST_POLYGLOAT_API_PORT}:8080"
      - 8091:8091
    environment:
      - polygloat.internal.populate=true
      - polygloat.internal.controllerEnabled=true
      - "polygloat.screenshots-url=http://localhost:8201/screenshots"
      - polygloat.authentication.needs-email-verification=true
      - polygloat.authentication.registrations-allowed=true
      - polygloat.internal.fake-emails-sent=true
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8091,server=y,suspend=n