version: '3'
services:
  app:
    container_name: ${TEST_POLYGLOAT_CONTAINER_NAME}
    image: polygloat/polygloat:${TEST_POLYGLOAT_SERVER_VERSION}
    ports:
      - "${TEST_POLYGLOAT_API_PORT}:8080"
    environment:
      - polygloat.internal.controller-enabled=true
      - polygloat.internal.populate=true