name: Test

on:
  push:
    branches-ignore:
      "prerelease-*"

jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Npm install
        run: npm install

      - name: Build with local api url
        run: apiUrl=http://localhost:8201/api/ npm run build

      - name: Start docker stack
        run: |
          docker-compose --env-file .test.docker.env -f test-docker-compose.yml up -d
          until docker logs --since 5m polygloat_webapp_test | grep -m 1 "started on port(s): 8080"; do : ;done

      - name: Run the tests
        run: |
          export CYPRESS_DEFAULT_PASSWORD=$(docker exec polygloat_webapp_test cat /data/initial.pwd)
          npm run serve & npm run cy:run

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*